<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="DataStore.fs" />
    <Compile Include="Loader.fs" />
    <Compile Include="BinaryInteraction.fs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../data/*.json" CopyToOutputDirectory="PreserveNewest" LinkBase="data" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Ganfoss.ROP" Version="1.2.0" />
    <PackageReference Include="FSharp.SystemTextJson" Version="1.3.13" />
    <PackageReference Update="FSharp.Core" Version="10.1.401" />
    <ProjectReference Include="../WhbThermo.Domain/WhbThermo.Domain.fsproj" />
  </ItemGroup>
</Project>
